[package]
name = "tc-error"
version = "0.4.0"
authors = ["haydn@tinychain.net"]
edition = "2018"
description = "TinyChain's generic error struct"
license = "Apache-2.0"
repository = "https://github.com/haydnv/tinychain.git"
readme = "README.md"

keywords = ["tinychain", "error", "service", "mesh"]
categories = ["data-structures", "rust-patterns"]

[dependencies]
destream = "0.5"
serde = "1.0"
