[package]
name = "tc-math"
version = "0.1.0"
authors = ["haydn@tinychain.net"]
edition = "2018"
description = "Mathematical algorithms for TinyChain tensors. Unstable."
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/haydnv/tinychain.git"

keywords = ["tinychain", "tensor", "math"]
categories = ["algorithms", "concurrency", "mathematics", "science"]

[dependencies]
log = { version = "0.4", features = ["release_max_level_warn"] }
tc-btree = "0.3"
tc-error = "0.4"
tc-transact = { version = "0.10", features = ["tensor"] }
tc-value = "0.3"
tc-table = "0.2"
tc-tensor = "0.3"
tcgeneric = "0.2.5"
