[package]
name = "tc-math"
version = "0.1.0"
authors = ["haydn@tinychain.net"]
edition = "2018"
description = "Mathematical algorithms for TinyChain tensors. Unstable."
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/haydnv/tinychain.git"

keywords = ["tinychain", "tensor", "math"]
categories = ["algorithms", "concurrency", "mathematics", "science"]

[dependencies]
log = { version = "0.4", features = ["release_max_level_warn"] }
tc-error = { path = "../error" }
tc-tensor = { path = "../tensor" }
tc-transact = { path = "../transact", features = ["tensor"] }
tcgeneric = { path = "../generic" }
